extends:
  - eslint:recommended
parser: babel-eslint
rules:
  complexity:
    - error
    - 10
  no-await-in-loop: warn
  no-eval: error
  no-implied-eval: error
  prefer-promise-reject-errors: warn
  no-var: error